### ISSUE TITLE
Create mockups

### ISSUE THREAD

**Issue by limit85** [gs-ndis/emarket#8]
Please create next mockups:
- for dialogs, that will be used on http://catalog-alpha.showthething.com/supportItem/testId for adding variant/relatedItem
- login / signup pages
- admin page: user list, user edit etc

**Comment by onthebreeze** [comment]
Just a few words about these admin features to add variants and related items.

I think we need a separate admin function to add new items. Probably an action similar to adding users.   Please note that creating a new item means that we need to provide a form with all the fields in the "SupportItem" entity shown at https://github.com/gs-ndis/emarket/blob/master/docs/SupportItemsAndVariants.md AND it also needs to have a repeating form to add any number of "VariantConfiguration" rows to an item.   

Then on http://catalog-alpha.showthething.com/supportItem/testId there are some edit buttons:
- The edit button at item level will allow the admin user to edit the item using the same form as the create new item.  So this will update item level information and allow to add / remove variantConfiguration lines.
- the "Add Variant" action will prompt the user with a form to add a new variant for that item.
- the add related item will only provide a search box (and allow to select which matching result to relate) because we will assume that we can only create a relationship to an item that already exists.

**Comment by fritzelemino** [comment]
Hi @limit85 and @onthebreeze , 

Please check these pop ups and let me know your thoughts

https://www.dropbox.com/sh/b0xr15evgkiprtf/AABAmS7_00ftfKTWRBk2mBUja?dl=0

Regards,

**Comment by fritzelemino** [comment]
Hi @limit85 , 

Can you please provide a list of these admin pages we need to create?

Also so you have any addition instructions for these pages?

Thank you 

Regards,

**Comment by limit85** [comment]
Hi @fritzelemino ,
Pop ups look nice, thanks

login by the following link:
http://catalog-alpha.showthething.com/login
admin@admin.com / admin

after this http://catalog-alpha.showthething.com/admin/users page will be available to you
I need mockup's at least for user managent page, meaning:
- table with list of users. this table contains filters as Text and Multiselect, also pagination
- edit/add user

Also I need a mockup for login / sign up pages, and please let me know where I can place these buttons.

**Comment by fritzelemino** [comment]
Hi @limit85 , 

Thank you for this information. this is noted.

Regards,

**Comment by fritzelemino** [comment]
Hi @limit85 , please check these for the log in and sign up pages. Let me know if I missed anything specially for the sign up form. 

https://www.dropbox.com/sh/3w1mz1uo4ojhd2n/AAApKV3bwGTbzl_E_Mr1puoTa?dl=0

Thank you.

**Comment by limit85** [comment]
Hi @fritzelemino ,
Login/signup pages looks nice. Where I should place these forms related to header/footer? Below banner with search? And where I should place login/signup buttons?

**Comment by fritzelemino** [comment]
Hi @limit85 , 

If possible it's completely they same as I designed it. no header , no footer. but when they click the logo they'll be back to the standard pages. Let me see where we can place the log in/signup buttons.

**Comment by fritzelemino** [comment]
Please check this one for the login and sign up button placement.

https://gyazo.com/ba3d8b19f2af2806183df1b7aedcf61e

Let me know if that works.

**Comment by fritzelemino** [comment]
Hi @limit85 , 

Please check the Manage users screen here, 

https://www.dropbox.com/sh/h51nqsm65777led/AACcYCvJAhNwxisoSsi4pVnpa?dl=0

Let me know if I missed anything.

**Comment by limit85** [comment]
Hi @fritzelemino ,

Sorry for a late reply.
I understood the idea where we can place login/signup buttons. Thanks.
Also thank you for mockups for admin manage users page, but I have a question:
we need any panel (or menu bar?) for navigation by admin pages. It is planned to have 3-4 admin sections in the whole, meaning now we will have: Users, Variants, Settings. Can you please point where better to place this block?
Also please provide me the mockups in PSD format. After that I think this issue can be closed.

Thanks,
Alex
